"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY', 'django-insecure-dev-key-change-in-production')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'False') == 'True'

ALLOWED_HOSTS = [
    "sensor.nexcareapp.com",
    "api.nexcareapp.com",
    "www.link-hash.com",
    "link-hash.com",
    "linkhash.jrai.space",
    "localhost",
    "127.0.0.1",
]
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

CSRF_TRUSTED_ORIGINS = [
    "https://sensor.nexcareapp.com",
    "https://api.nexcareapp.com",
    "https://www.link-hash.com",
    "https://link-hash.com",
    "https://linkhash.jrai.space",
]


# Application definition

INSTALLED_APPS = [
    "daphne",
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'channels',
    'market',
    "django.contrib.humanize",
    "ckeditor",
    "ckeditor_uploader",
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # ✅ Add WhiteNoise
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

# WhiteNoise configuration
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# CKEditor 업로더 경로
CKEDITOR_UPLOAD_PATH = "announcements/"

# (선택) 에디터 툴바 커스터마이즈
CKEDITOR_CONFIGS = {
    "default": {
        "toolbar": "full",
        "height": 360,
        "width": "100%",
        "extraPlugins": ",".join(["uploadimage", "image2"]),
    }
}


# partnership related settings
SOLANA_RPC_URL = "https://api.mainnet-beta.solana.com"  # 또는 Helius RPC URL 권장
LINKHASH_LHX_MINT = "9LrT8gAKJ5qUJA1wJoQRrVfapJGrNnU2ca5UYiJipump"  # ✅ LHX mint (너가 CA로 쓰는 거)
LINKHASH_DEV_WALLET = "GkWMcnSNQP4aTVZruJMSwjhzW3VvEza3iZXi3NEwzPKE"

BASIC_AD_LHX = 100_000
PREMIUM_AD_LHX = 250_000

LHX_DECIMALS = 6

BASIC_AD_DAYS = 14
PREMIUM_AD_DAYS = 60

CAMPAIGN_FEE_WALLET = "9CN6FmD81w1azLpwdkvvwp3J8FFL5xwXkZ4vzYbYFecK"
CAMPAIGN_SUBMIT_LHX_FEE = 100

OPENAI_API_KEY = os.getenv('OPENAI_API_KEY', '')


CAMPAIGN_FEE_WALLET = "9CN6FmD81w1azLpwdkvvwp3J8FFL5xwXkZ4vzYbYFecK"
CAMPAIGN_SUBMIT_LHX_FEE = 100

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [("127.0.0.1", 6379)],
        },
    }
}

# ============================================================
# ✅ Celery (dynamic timer settlement, production)
# ============================================================
# Use a different Redis DB index from Channels to avoid noise
CELERY_BROKER_URL = "redis://127.0.0.1:6379/1"
CELERY_RESULT_BACKEND = "redis://127.0.0.1:6379/2"

CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"

# Use UTC since your Django TIME_ZONE = "UTC"
CELERY_TIMEZONE = "UTC"

# Reliability
CELERY_TASK_ACKS_LATE = True
CELERY_WORKER_PREFETCH_MULTIPLIER = 1

# ============================================================
# ✅ Celery Beat (watchdog safety net)
# - This prevents "timer hits 0 and session never advances" after restarts.
# ============================================================
from celery.schedules import crontab

CELERY_BEAT_SCHEDULE = {
    "update-hourly-predictions": {
        "task": "market.tasks.update_hourly_predictions",
        "schedule": crontab(minute=0, hour="*"),
    },
    "sync-sponsored-dex": {
        "task": "market.tasks.sync_sponsored_dex_metrics",
        "schedule": crontab(minute=2, hour="*"),
    },
    "update-market-snapshots": {
        "task": "market.tasks.update_market_snapshots",
        "schedule": crontab(minute=5, hour="*"),
    },
}

DATA_UPLOAD_MAX_NUMBER_FIELDS = 500000


ASGI_APPLICATION = "config.asgi.application"